# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto101', '0002_consulta_medico_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='tipo_consulta',
        ),
    ]
