# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto101', '0003_remove_consulta_tipo_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projeto101.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projeto101.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observacoes',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
    ]
