# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projeto101', '0008_auto_20160817_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 1, 43, 50, 898487, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora_consulta',
            field=models.TimeField(default=datetime.datetime(2016, 8, 18, 1, 44, 2, 455493, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
