# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 02:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projeto101', '0009_auto_20160817_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 2, 10, 35, 553115, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
