# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-20 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto101', '0011_auto_20160820_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
